export const MOCK_DATA = [
  {
    category: 'Entertainment: Video Games',
    type: 'multiple',
    difficulty: 'easy',
    question: 'Which game did NOT get financed via Crowdfunding?',
    correct_answer: 'Enter the Gungeon',
    incorrect_answers: ['Town of Salem', 'Undertale', 'Tower Unite'],
  },
  {
    category: 'Entertainment: Comics',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What was the name of the first Robin in the Batman comics?',
    correct_answer: 'Dick Grayson',
    incorrect_answers: ['Bruce Wayne', 'Jason Todd', 'Tim Drake'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Who plays the Nemesis in the Resident Evil movies?',
    correct_answer: 'Matthew Taylor',
    incorrect_answers: ['Jason Dip', 'Eric Mabius', 'Jimmy Matts'],
  },
  {
    category: 'Mythology',
    type: 'multiple',
    difficulty: 'hard',
    question: 'Nidhogg is a mythical creature from what mythology?',
    correct_answer: 'Norse',
    incorrect_answers: ['Egyptian', 'Greek', 'Hindu'],
  },
  {
    category: 'Entertainment: Television',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'In the show &quot;Tengen Toppa Gurren Lagann&quot; what is the name of the character who force everyone to live underground?',
    correct_answer: 'Lordgenome',
    incorrect_answers: ['Kingloname', 'Lord Genome', 'King Loname'],
  },
  {
    category: 'Entertainment: Board Games',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'Which card is on the cover of the Beta rulebook of &quot;Magic: The Gathering&quot;?',
    correct_answer: 'Bog Wraith',
    incorrect_answers: ['Island', 'Rock Hydra', 'Elvish Archers'],
  },
  {
    category: 'Entertainment: Video Games',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What is the name of the main protagonist in &quot;Xenoblade Chronicles&quot;?',
    correct_answer: 'Shulk',
    incorrect_answers: ['Reyn', 'Fiora', 'Dunban'],
  },
  {
    category: 'History',
    type: 'multiple',
    difficulty: 'medium',
    question: 'In what year did Texas secede from Mexico?',
    correct_answer: '1836',
    incorrect_answers: ['1838', '1845', '1844'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'What is the name of the foley artist who designed the famous sounds of Star Wars, including Chewbacca&#039;s roar and R2-D2&#039;s beeps and whistles?',
    correct_answer: 'Ben Burtt',
    incorrect_answers: ['Ken Burns', 'Ralph McQuarrie', 'Miranda Keyes'],
  },
  {
    category: 'Geography',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What is the largest freshwater lake by volume?',
    correct_answer: 'Lake Baikal',
    incorrect_answers: ['Lake Superior', 'Lake Huron', 'Lake Michigan'],
  },
];
